name: nilm-ms-transformer
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
      - torch
      - jupyterlab
      - ipykernel
      - matplotlib
      - numpy
      - scikit-learn